/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Can({ position, rotation }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Combat/Can.glb");
  return (
    <group ref={group} position={position} dispose={null}>
      <group rotation={rotation} scale={300}>
        <mesh
          geometry={nodes.Can_Red_1.geometry}
          material={materials.LightGrey}
        />
        <mesh geometry={nodes.Can_Red_2.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Can_Red_3.geometry} material={materials.Red} />
      </group>
    </group>
  );
}

useGLTF.preload("/Combat/Can.glb");
