/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Telephone({ position, rotation }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Combat/Telephone.glb");
  return (
    <group ref={group} position={position} rotation={rotation} dispose={null}>
      <mesh
        geometry={nodes.SM_TelPoleSM_TelPole1_1.geometry}
        material={materials.lambert4SG}
      />
      <mesh
        geometry={nodes.SM_TelPoleSM_TelPole1_1_1.geometry}
        material={materials.lambert2SG}
      />
      <mesh
        geometry={nodes.SM_TelPoleSM_TelPole1_1_2.geometry}
        material={materials.lambert3SG}
      />
      <mesh
        geometry={nodes.SM_TelPoleSM_TelPole1_1_3.geometry}
        material={materials.lambert5SG}
      />
    </group>
  );
}

useGLTF.preload("/Combat/Telephone.glb");
